# Generated by Django 4.0.6 on 2022-10-09 13:03

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utube_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField(default=False)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('hastags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyright', to='utube_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribee', to='utube_app.author')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='utube_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utube_app.author')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utube_app.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_creation', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utube_app.author')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utube_app.video')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='subscribed_to',
            field=models.ManyToManyField(null=True, through='utube_app.Subscription', to='utube_app.author'),
        ),
    ]
