# Generated by Django 4.0.6 on 2022-10-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utube_app', '0002_author_video_subscription_likes_comments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
