# Generated by Django 4.0.6 on 2022-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utube_app', '0004_rename_hastags_video_hashtags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hashtags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
