# Generated by Django 4.0.6 on 2022-10-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatechat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicChat',
        ),
    ]
