# Generated by Django 3.2.9 on 2022-10-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatechat', '0003_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='chatId',
            field=models.IntegerField(default=0),
        ),
    ]
